script: mvn -P generator test

deploy:
- provider: script
  script: mvn package deploy -s ./.travis.maven-settings.xml -P generator -P release
  on:
    tags: true

env:
  global:
    - BINTRAY_USER: kenwenzel
    - secure: "EcBRVsg0EzWY5sfXGtXvFCafoO0YVk91WIhBtp39gMHtuFYg/JrvrDLej5x4S1FAkSBLNke9SSE1bl+XeYo6GK+NSF3RcfQzz7aIU4QhPB6xwX5oRPzvXBHb74lDxLUNXh0keTg7pXmIWXnRzRSkaYqt0KFCU1Opwu5jZfv3neYuYc3jZdgjuYDk8g5158k7fXhXlAds93G+ungjYTECS5AWi68pEoTKV4BMgnfB3QaoiYgSWak+sqSrdqs7o5kwsUwFSd5mxbjCL1+3o1YIZz859cIeYb+2RzRbFjBRuWWhXk+9vc70dgCPaLbj37hgbU4QDkGAjAqWHPo8KGcfynLuzAv45W0BOeyXX74uBTVwPh8pq+7Mb209DVjwm4h5k7mOpiKANSkB+ema8Hi58cv0AxQsgP+vOFDksNWsrwWEGX1QEKd+YaZtcSDZhWOd2WpH1lv4gtIe5zzigVJXImD+mcvYK4PdQ5h8TAAAoq+unKnrpZartaVGU00S8Lsg6ABiz7ekULkqZTGr8BBtK94OM4OFnwuSUFB01IfyKvDulWo956UR90xakSw99FYNvV/Lt/kdD3UDZDEGub7Zj4CeGRu53Lz862/oWN5jymwVOULoSzlKG8xRmZGnmIde6qzlH9CKM/fYa+rzkRZWPQWjxA2rvxZXU0/yCwVw6n4="
